name: continuous release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          submodules: recursive
      
      - name: Archive Build Result
        uses: thedoctor0/zip-release@0.7.1
        with:
          filename: 'turbo_nerf.zip'

      - name: Generate Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: 'turbo_nerf.zip'
          bodyFile: 'docs/release.md'
          commit: ${{ github.sha }}
          makeLatest: true
          name: 'TurboNeRF Blender Addon'
          prerelease: true
          replacesArtifacts: true
          tag: 'pre-release'
          token: ${{ secrets.GITHUB_TOKEN }}
