name: continuous release
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: false
        default: 'pre-release'

  repository_dispatch:
    types: [release]


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          submodules: recursive
      
      - name: Create Addon Folder Structure
        run: |
          mkdir -p /tmp/turbo_nerf
          cp -R . /tmp/turbo_nerf
      
      - name: Archive Build Result
        uses: thedoctor0/zip-release@0.7.1
        with:
          directory: '/tmp'
          path: 'turbo_nerf'
          exclusions: '*/.git*, */.github*'
          filename: '/tmp/TurboNeRF-BlenderAddon.zip'
      
      - name: Set Release Tag
        # if ${{ github.event.client_payload.tag }} is set then use it, otherwise use the input tag
        run: |
          echo 'RELEASE_TAG=${{ github.event.client_payload.tag || inputs.tag }}' >> $GITHUB_ENV
      
      - name: Set Release URL
        run: |
          echo "RELEASE_URL=${{ github.event.client_payload.release_url:-https://github.com/JamesPerlman/TurboNeRF/releases/tag/${{ env.RELEASE_TAG }}}}" >> $GITHUB_ENV

      - name: Generate Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: '/tmp/TurboNeRF-BlenderAddon.zip'
          body: 'Please download [PyTurboNeRF ${{ env.RELEASE_TAG }}](${{ env.RELEASE_URL }}) along with this addon.'
          commit: ${{ github.sha }}
          makeLatest: true
          name: 'TurboNeRF Blender Addon'
          prerelease: true
          replacesArtifacts: true
          tag: ${{ env.RELEASE_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
  notify-discord:
    runs-on: ubuntu-20.04
    needs: build-pylib-binaries
    steps:
      - name: Dispatch Release Notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "A new version of the Blender addon is now available. [TurboNeRF-Blender ${{ inputs.tag }}](${{ env.RELEASE_URL }})""

