name: continuous release
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  repository_dispatch:
    types: [release]

inputs:
  tag:
    description: 'Tag to release'
    required: false
    default: 'pre-release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          submodules: recursive
      
      - name: Create Addon Folder Structure
        run: |
          mkdir -p /tmp/turbo_nerf
          cp -R . /tmp/turbo_nerf
      
      - name: Archive Build Result
        uses: thedoctor0/zip-release@0.7.1
        with:
          directory: '/tmp'
          path: 'turbo_nerf'
          exclusions: '*/.git*, */.github*'
          filename: '/tmp/TurboNeRF-BlenderAddon.zip'
      
      - name: Set Release Tag
        # if ${{ github.event.client_payload.tag }} is set then use it, otherwise use the input tag
        run: |
          echo "RELEASE_TAG=${{ github.event.client_payload.tag || inputs.tag }}" >> $GITHUB_ENV

      - name: Generate Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: '/tmp/TurboNeRF-BlenderAddon.zip'
          body: 'Please download [PyTurboNeRF ${{ env.RELEASE_TAG }}](https://github.com/JamesPerlman/TurboNeRF/releases/tag/${{ env.RELEASE_TAG }}) along with this addon.'
          commit: ${{ github.sha }}
          makeLatest: true
          name: 'TurboNeRF Blender Addon'
          prerelease: true
          replacesArtifacts: true
          tag: ${{ env.RELEASE_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
